# Define algoritmo de alocação de processos na memória:
HEAP_x		:= heap_4.c 

# Nome dos arquivos processados:
TARGET		:= OUT

# Pasta da raíz do projeto:
ROOT_DIR 	:= ..

# Nome da pasta do atual projeto:
USER_DIR 	:= $(ROOT_DIR)/$(notdir $(shell pwd))

# use libraries, please add or remove when you use or remove it.
# SRC  += $(STM32F1_SRC_DIR)/stm32f10x_adc.c
# SRC  += $(STM32F1_SRC_DIR)/stm32f10x_exti.c

# Chamada do makefile principal do projeto: 
include ../Makefile
